config/routes.rb
Rails.application.routes.draw do
 
  resources :commissioning_forms do
    collection do
      get :form_setup    
    end
  member do 
       get :printable
     end
  end
   
root 'commissioning_forms#index'

resources :sessions, only: [:new, :create, :destroy]
resources :users

end

app/models/commissioning_form.rb
class CommissioningForm < ActiveRecord::Base
has_many :mods
has_many :inverters
belongs_to :user
accepts_nested_attributes_for :mods, :inverters

validates_presence_of :job


def self.search(query)
where("job like ?", "%#{query}%")
#where("customer_name like ?", "%#{query}%") # works just not in use
end

end

app/models/inverter.rb
class Inverter < ActiveRecord::Base
belongs_to :commissioning_form
end

app/models/mod.rb
class Mod < ActiveRecord::Base

belongs_to :commissioning_form
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
 attr_accessor :confirmation
   
has_many :commissioning_forms
   #EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  #validates :name, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  #validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  #validates_length_of :password, :in => 6..20, :on => :create

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


def current_user
	User.where(id: session[:user_id]).first
end

def login_required
    redirect_to(new_session_path) if current_user.blank?
  end

helper_method :current_user


end

app/controllers/commissioning_forms_controller.rb
class CommissioningFormsController < ApplicationController
before_filter :login_required
  before_action :set_commissioning_form, only: [ :update, :destroy]

  def form_setup
  end

  def index
  pagination = Pagination.new
  params[:page] = pagination.paginate(params[:page].to_i, params[:request], CommissioningForm.count, 10)
@page = params[:page].to_i
       
       if params[:search]
         @commissioning_forms = CommissioningForm.search(params[:search]).order("created_at ASC").limit(10) 
         
      else
    @commissioning_forms = CommissioningForm.limit(10).offset(params[:page]).order("created_at ASC")
  end
  end

  def show
    @commissioning_form = CommissioningForm.includes([:mods,:inverters]).find(params[:id])
  end

def printable 
@commissioning_form = CommissioningForm.includes([:mods,:inverters]).find(params[:id])
 render :layout => false
end
  
  def new
    @commissioning_form = CommissioningForm.new
  @commissioning_form.mods.build
  
   @inverter_number = 0
   params[:type_of_inverters].to_i.times do
   @commissioning_form.inverters.build
   end
  end

  
  def edit
  @commissioning_form = CommissioningForm.includes([:mods,:inverters]).find(params[:id])
  end

  
  def create
    @commissioning_form = CommissioningForm.new(commissioning_form_params)

#if params[:commit] == "save as draft"
 # @commissioning_form.draft = true
 #end
 @commissioning_form.user = current_user
      if @commissioning_form.save
       
       flash[:notice] = "Commissioning form was successfully created."
      redirect_to @commissioning_form 
       
      else
      flash.now[:errors] = "Error in creating form"
       render :new 
     end
    end
  

  def update
    if @commissioning_form.update(commissioning_form_params)
     flash[:notice] = "Commissioning form was successfully created."
    redirect_to @commissioning_form
      else
      flash.now[:errors] = "Error in updating form"
      render :edit 
      
      end
    end
  

  
  def destroy
    @commissioning_form.destroy
        flash[:notice] = 'Commissioning form was successfully destroyed.'
     redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_commissioning_form
      @commissioning_form = CommissioningForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def commissioning_form_params
      params.require(:commissioning_form).permit(:user_id,:draft, :send_email, :commissioning_date, :employee_name, :job, :customer_name, :job_type, :system_size, :location, :physical_address, :mailing_address, :parcel_id, :customer_phone, :customer_email, :permit, :installation_completed, :net_meter_installed, :wapa_account, :project_notes,
       mods_attributes: [:mod_type, :qty, :commissioning_form_id],
       inverters_attributes: [:inverter_type, :qty_of_inverter, :total_mods_to_inv, :strings, :avg_voltage_dc, :ocpd, :load_center_size, :lc_main_wire_gauge, :kwh_total, :commissioning_form_id])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create 
@user = User.find_by_email(params[:email])
if @user && @user.authenticate(params[:password])
	session[:user_id] = @user.id
redirect_to root_path
else
	render 'new'
end
end

def destroy
session[:user_id] = nil
redirect_to new_session_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
  @user = User.new
  end

def create
@user = User.new(user_params)
if params[:prosolar_password] != ENV['COMPANY_PASSWORD']
	flash.now[:notice] = "prosolar password incorrect "
	render 'new'
elsif @user.save
	session[:user_id] = @user.id
	redirect_to root_path
else
	render 'new'
end
end

def show
end

private

def user_params
	params.require(:user).permit(:name, :email, :password, :password_confirmation)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commissioning_forms_helper.rb
module CommissioningFormsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/commissioning_forms/_form.html.erb
<%= form_for(@commissioning_form) do |f| %>
  <% if @commissioning_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@commissioning_form.errors.count, "error") %> prohibited this commissioning_form from being saved:</h2>

      <ul>
      <% @commissioning_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h3>Customer Info</h3>
  <div class="field">
    <%= f.label :job %><br>
    <%= f.text_field :job %>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.text_field :customer_name %>
  </div>
  <div class="field">
    <%= f.label :job_type %><br>
    <%= f.select :job_type, ["Commercial", "Residential ", "Other"] %>
  </div>
  <div class="field">
    <%= f.label :system_size %><br>
    <%= f.number_field :system_size %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :physical_address %><br>
    <%= f.text_field :physical_address %>
  </div>
  <div class="field">
    <%= f.label :mailing_address %><br>
    <%= f.text_field :mailing_address %>
  </div>
  <div class="field">
    <%= f.label :parcel_id %><br>
    <%= f.text_field :parcel_id %>
  </div>
  <div class="field">
    <%= f.label :customer_phone %><br>
    <%= f.number_field :customer_phone %>
  </div>
  <div class="field">
    <%= f.label :customer_email %><br>
    <%= f.text_field :customer_email %>
  </div>


  <br>
<h3> Modules </h3>
<%= f.fields_for(:mods) do |mod_form| %>
<p>
<%= mod_form.label :mod_type %>
<br>
<%= mod_form.text_field :mod_type %>
</p>
<p>
<%= mod_form.label :qty %>
<br>
<%= mod_form.text_field :qty %>
</p>
<% end %>
<br>



<%= f.fields_for(:inverters) do |inverter_form| %>
<% @inverter_number += 1 %>
<%= render :partial => 'inverter_form', :locals => {:f => inverter_form } %>
<% end %>


<br>
<h3> Electrical Info</h3>
  <div class="field">
    <%= f.label :permit %><br>
    <%= f.text_field :permit %>
  </div>
  <div class="field">
    <%= f.label :installation_completed %><br>
    <%= f.text_field :installation_completed %>
  </div>
  <div class="field">
    <%= f.label :net_meter_installed %><br>
    <%= f.text_field :net_meter_installed %>
  </div>
  <div class="field">
    <%= f.label :wapa_account %><br>
    <%= f.text_field :wapa_account %>
  </div>
  <div class="field">
    <%= f.label :project_notes %><br>
    <%= f.text_area :project_notes %>
  </div>
  <div class="actions">


    <%= f.label :commissioning_date %><br>
    <%= f.text_field :commissioning_date %>
  <br>
    <%= f.label :employee_name %><br>
    <%= f.text_field :employee_name %>
 <br>

<%= f.submit 'save' %> 
  </div>
<% end %>

app/views/commissioning_forms/_inverter_form.html.erb
<h3>Inverter<%="##{@inverter_number}"%></h3>
<p>
<%= f.label :inverter_type %>
<br>
<%= f.text_field :inverter_type %>
</p>
<p>
<%= f.label :qty_of_inverter %>
<br>
<%= f.select :qty_of_inverter, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20] %>
</p>
<%= f.label :strings %>
<br>
<%= f.select :strings, [1,2,3,4,5,6,7,8,9,10] %>
</p>
  <%= f.label :avg_voltage_dc %>
<br>
<%= f.number_field :avg_voltage_dc %>
</p>
<%= f.label :ocpd %>
<br>
<%= f.text_field :ocpd %>
</p>

<%= f.label :load_center_size %>
<br>
<%= f.number_field :load_center_size %>
</p>
<%= f.label :lc_main_wire_gauge %>
<br>
<%= f.select :lc_main_wire_gauge, [1,2,3,4,5,6,7,8,9,10,12] %>
</p>

<%= f.label :kwh_total %>
<br>
<%= f.number_field :kwh_total %>
</p>

 

app/views/commissioning_forms/_pagination.html.erb
<%= link_to "first", commissioning_forms_path( page: @page, request: "first") %>

<% if params[:search] %>
<a href="next" class="gray">Next</a>
<a href="back" class="gray">Back</a>
<% else %>
<% if params[:page] >= CommissioningForm.count - 10 %>
<a href="" class="gray">Next</a>
<% else %>
<%= link_to "next", commissioning_forms_path( page: @page, request: "next") %>
<% end %>

<% if params[:page] <= 0 %>
<a href="" class="gray">Back</a>
<% else %>
<%= link_to "back", commissioning_forms_path( page: @page, request: "back") %>
<% end %>
<% end %>
<%= link_to "last", commissioning_forms_path( page: @page, request: "last") %>

app/views/commissioning_forms/edit.html.erb
<h1>Editing commissioning_form</h1>

<%= render 'form' %>

<%= link_to 'Show', @commissioning_form %> |
<%= link_to 'Back', commissioning_forms_path %>

app/views/commissioning_forms/form_setup.html.erb
<div class="center">
<%= form_tag new_commissioning_form_path, method: :get do %>
<h3> Types of inverter on job </h3>
Types<%= select_tag "type_of_inverters", "<option>1</option><option>2</option><option>3</option><option>4</option><option>5</option>".html_safe %>
<br>
<br>
<%= submit_tag "Next Section" %>
<% end %>
<%= link_to 'Back', commissioning_forms_path %>
</div>

app/views/commissioning_forms/index.html.erb
<h1>Listing commissioning_forms</h1>

     
      Job
      
    
<%= form_tag( commissioning_forms_path, method: :get ) do %>
<%= text_field_tag :search %>
<%= submit_tag "search" %>
<% end %>
  
<br>
<%= render :partial => 'pagination' %>
<br>

 <% if @commissioning_forms.empty? %>
 <p>No Matching Query </p>
 <% else %>
    <% @commissioning_forms.each do |commissioning_form| %>

      <br>
       <%= link_to 'Open', commissioning_form %>
      <%= commissioning_form.job %>
      
     
    
    <% end %>
<% end %>
<br>
<br>
<%= link_to 'New Commissioning form', form_setup_commissioning_forms_path %>

app/views/commissioning_forms/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', :back %>
<%= link_to 'Index', root_path %>

app/views/commissioning_forms/printable.html.erb
<h2>Customer Info </h2>
<p>
  <strong>Commissioning date:</strong>
  <%= @commissioning_form.commissioning_date %>
</p>

<p>
  <strong>Employee name:</strong>
  <%= @commissioning_form.employee_name %>
</p>

<p>
  <strong>Job:</strong>
  <%= @commissioning_form.job %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @commissioning_form.customer_name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @commissioning_form.job_type %>
</p>

<p>
  <strong>System size:</strong>
  <%= @commissioning_form.system_size %>
</p>

<p>
  <strong>Location:</strong>
  <%= @commissioning_form.location %>
</p>

<p>
  <strong>Physical address:</strong>
  <%= @commissioning_form.physical_address %>
</p>

<p>
  <strong>Mailing address:</strong>
  <%= @commissioning_form.mailing_address %>
</p>

<p>
  <strong>Parcel:</strong>
  <%= @commissioning_form.parcel_id %>
</p>

<p>
  <strong>Customer phone:</strong>
  <%= @commissioning_form.customer_phone %>
</p>

<p>
  <strong>Customer email:</strong>
  <%= @commissioning_form.customer_email %>
</p>

<h2>Modules</h2>
<% @commissioning_form.mods.each do |panel| %>
<p>
<strong>Type:</strong>
<%= panel.mod_type %>
</p>
<p>
<strong>QTY:</strong>
<%= panel.qty %>
</p>
<% end %>

<h2>Inverter Info </h2>
<% @commissioning_form.inverters.each do |inverter| %>
<p>
<strong>Inverter Type:</strong>
<%= inverter.inverter_type%>
</p>
<p>
<strong>Inverter Qty:</strong>
<%= inverter.qty_of_inverter%>
</p>
<p>
<strong>Total Modules for Inverter:</strong>
<%= inverter.total_mods_to_inv%>
</p>
<p>
<strong>Strings:</strong>
<%= inverter.strings%>
</p>
<p>
<strong>Avg Voltage DC:</strong>
<%= inverter.avg_voltage_dc%>
</p>
<p>
<strong>OCPD:</strong>
<%= inverter.ocpd%>
</p>
<p>
<strong>Load Center Size:</strong>
<%= inverter.load_center_size%>
</p>
<p>
<strong>LC Main Wire Gauge:</strong>
<%= inverter.lc_main_wire_gauge %>
</p>
<p>
<strong>kwh total:</strong>
<%= inverter.kwh_total %>
</p>

<% end %>


<h2> Electrical Info</h2>
<p>
  <strong>Permit:</strong>
  <%= @commissioning_form.permit %>
</p>

<p>
  <strong>Installation completed:</strong>
  <%= @commissioning_form.installation_completed %>
</p>

<p>
  <strong>Net meter installed:</strong>
  <%= @commissioning_form.net_meter_installed %>
</p>

<p>
  <strong>Wapa account:</strong>
  <%= @commissioning_form.wapa_account %>
</p>

<p>
  <strong>Project notes:</strong>
  <%= @commissioning_form.project_notes %>
</p>

app/views/commissioning_forms/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Customer Info </h2>
<p>
  <strong>Commissioning date:</strong>
  <%= @commissioning_form.commissioning_date %>
</p>

<p>
  <strong>Employee name:</strong>
  <%= @commissioning_form.employee_name %>
</p>

<p>
  <strong>Job:</strong>
  <%= @commissioning_form.job %>
</p>

<p>
  <strong>Customer name:</strong>
  <%= @commissioning_form.customer_name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @commissioning_form.job_type %>
</p>

<p>
  <strong>System size:</strong>
  <%= @commissioning_form.system_size %>
</p>

<p>
  <strong>Location:</strong>
  <%= @commissioning_form.location %>
</p>

<p>
  <strong>Physical address:</strong>
  <%= @commissioning_form.physical_address %>
</p>

<p>
  <strong>Mailing address:</strong>
  <%= @commissioning_form.mailing_address %>
</p>

<p>
  <strong>Parcel:</strong>
  <%= @commissioning_form.parcel_id %>
</p>

<p>
  <strong>Customer phone:</strong>
  <%= @commissioning_form.customer_phone %>
</p>

<p>
  <strong>Customer email:</strong>
  <%= @commissioning_form.customer_email %>
</p>

<h2>Modules</h2>
<% @commissioning_form.mods.each do |panel| %>
<p>
<strong>Type:</strong>
<%= panel.mod_type %>
</p>
<p>
<strong>QTY:</strong>
<%= panel.qty %>
</p>
<% end %>

<h2>Inverter Info </h2>
<% @commissioning_form.inverters.each do |inverter| %>
<p>
<strong>Inverter Type:</strong>
<%= inverter.inverter_type%>
</p>
<p>
<strong>Inverter Qty:</strong>
<%= inverter.qty_of_inverter%>
</p>
<p>
<strong>Total Modules for Inverter:</strong>
<%= inverter.total_mods_to_inv%>
</p>
<p>
<strong>Strings:</strong>
<%= inverter.strings%>
</p>
<p>
<strong>Avg Voltage DC:</strong>
<%= inverter.avg_voltage_dc%>
</p>
<p>
<strong>OCPD:</strong>
<%= inverter.ocpd%>
</p>
<p>
<strong>Load Center Size:</strong>
<%= inverter.load_center_size%>
</p>
<p>
<strong>LC Main Wire Gauge:</strong>
<%= inverter.lc_main_wire_gauge %>
</p>
<p>
<strong>kwh total:</strong>
<%= inverter.kwh_total %>
</p>

<% end %>


<h2> Electrical Info</h2>
<p>
  <strong>Permit:</strong>
  <%= @commissioning_form.permit %>
</p>

<p>
  <strong>Installation completed:</strong>
  <%= @commissioning_form.installation_completed %>
</p>

<p>
  <strong>Net meter installed:</strong>
  <%= @commissioning_form.net_meter_installed %>
</p>

<p>
  <strong>Wapa account:</strong>
  <%= @commissioning_form.wapa_account %>
</p>

<p>
  <strong>Project notes:</strong>
  <%= @commissioning_form.project_notes %>
</p>
<%= link_to 'Destroy', @commissioning_form, method: :delete, data: { confirm: 'Are you sure?' } %>
<%= link_to 'Edit', edit_commissioning_form_path(@commissioning_form) %> |
<%= link_to 'Back', commissioning_forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Prosolar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
<%= link_to "Log Out", session_path(current_user), method: :delete %>
<% else %>
<%= link_to "Log In", new_session_path %>
<%= link_to "Sign Up", new_user_path %>
<% end %>

<% flash.each do |key, value| %>
<%= value %>
<% end %>

<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/users/new.html.erb
<h1> New User </h1>

<%= form_for(@user) do |f| %>
<p>
	<%= f.label :name %>
	<%= f.text_field :name %>
</p>
<p>
	<%= f.label :email%>
	<%= f.email_field :email %>
</p>
<p>
	<%= f.label :password %>
	<%= f.password_field :password %>
</p>
 <p> Password Confirmation: <%= f.password_field :password_confirmation%> </p>
<p>
	<%= f.label :prosolar_password %>
	<%= text_field_tag :prosolar_password %>
</p>
<%= f.submit %>
<% end %>